on:
  workflow_run:
    workflows: ["SonarCloud analysis"]
    types:
      - completed

jobs:
  Build-and-push-to-GCC:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: hue-intern
      PROJECT_ID: stage-kora-dokbua
      REGION: europe-west4
      GAR_LOCATION: europe-west4-docker.pkg.dev/stage-kora-dokbua/hue-intern

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: authenticate to GAR
        run: gcloud auth configure-docker \europe-west4-docker.pkg.dev
      

      - uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev/stage-kora-dokbua/hue-intern --quiet

      # - name: Build image
      #   run: docker build -t hue-intern .
      - name: Build image
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb

      - name: Docker tag
        run: docker tag hue-intern ${{ env.GAR_LOCATION }}/hue-intern:${{ GITHUB_SHA::8 }}
     

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: hue-intern/app

      - name: Push Docker Image to Artifact Registry
        run: docker push ${{ env.GAR_LOCATION }}/hue-intern:${{ GITHUB_SHA::8 }}





          
        


