on:
  workflow_run:
    workflows: ["SonarCloud analysis"]
    types:
      - completed

jobs:
  Build-and-push-to-GCC:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: hue-intern
      PROJECT_ID: stage-kora-dokbua
      REGION: europe-west4
      GAR_LOCATION: europe-west4-docker.pkg.dev

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image and send to GAR
        run: docker build . --file Q42-KoraD/hue-intern --tag ${{ env.GAR_LOCATION }}
        working-directory: hue-intern

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: v0.0.1

        run: docker push ${{ env.GAR_LOCATION }}


