on:
  workflow_run:
    workflows: ["SonarCloud analysis"]
    types:
      - completed

jobs:
  Build-and-push-to-GCC:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: hue-intern
      PROJECT_ID: stage-kora-dokbua
      REGION: europe-west4
      GAR_LOCATION: europe-west4-docker.pkg.dev/stage-kora-dokbua/hue-intern/

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev/stage-kora-dokbua/hue-intern/ --quiet

      - name: Build image
        run: docker build -f Dockerfile .

      - name: Push Docker Image to Artifact Registry
        run: docker push ${{ env.GAR_LOCATION }}:latest


